### ISSUE TITLE
GUI crashes when using qtconsole for mantid_ipython_console.py

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#104]
ADDIE breaks with the an error message (shown below) when you this header in `addie/mantid_ipython_console.py` on the anaylsis cluster. Basically, when you use `qtconsole`:

```
try:
    from qtconsole.rich_ipython_widget import RichIPythonWidget
    from qtconsole.inprocess import QtInProcessKernelManager
except:
    from IPython.qt.console.rich_ipython_widget import RichIPythonWidget
    from IPython.qt.inprocess import QtInProcessKernelManager


```
Machine info (from running `lsb_release -a`):
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 7.5 (Maipo)
Release:	7.5
Codename:	Maipo

Error message produced:
```
Traceback (most recent call last):
  File "build/scripts-2.7/addie", line 2266, in <module>
    main()
  File "build/scripts-2.7/addie", line 2261, in main
    form = MainWindow()
  File "build/scripts-2.7/addie", line 125, in __init__
    self.ui.dockWidget_ipython.setup()
  File "/SNS/users/ntm/software/addie/build/lib/addie/ipythondockwidget.py", line 21, in setup
    self.iPythonWidget = mantid_ipython_widget.MantidIPythonWidget()
  File "/SNS/users/ntm/software/addie/build/lib/addie/mantid_ipython_widget.py", line 73, in __init__
    kernel_manager.start_kernel()
  File "/usr/lib/python2.7/site-packages/ipykernel/inprocess/manager.py", line 46, in start_kernel
    self.kernel = InProcessKernel(parent=self, session=self.session)
  File "/usr/lib/python2.7/site-packages/ipykernel/inprocess/ipkernel.py", line 72, in __init__
    super(InProcessKernel, self).__init__(**traits)
  File "/usr/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 58, in __init__
    kernel      = self,
  File "/usr/lib/python2.7/site-packages/IPython/config/configurable.py", line 337, in instance
    inst = cls(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 466, in __init__
    super(InteractiveShell, self).__init__(**kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/config/configurable.py", line 69, in __init__
    self.parent = parent
  File "/usr/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 430, in __set__
    new_value = self._validate(obj, value)
  File "/usr/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 451, in _validate
    return self.validate(obj, value)
  File "/usr/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 965, in validate
    self.error(obj, value)
  File "/usr/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 798, in error
    raise TraitError(e)
IPython.utils.traitlets.TraitError: The 'parent' trait of an InProcessInteractiveShell instance must be a Configurable or None, but a value of class 'ipykernel.inprocess.ipkernel.InProcessKernel' (i.e. <ipykernel.inprocess.ipkernel.InProcessKernel object at 0x7f9d04f660d0>) was specified.
```
This is re-occurring. Can we re-visit pointing to the Mantid version of this (found in `/opt/mantidnightly/bin/ipython_widget/mantid_ipython_widget.py` on analysis.sns.gov)

@peterfpeterson and @JeanBilheux , do you have any thoughts?

**Comment by marshallmcdonnell** [comment]
Fixed by #133
