### ISSUE TITLE
Python3 ui failure: switch from `pyuic` to `load_ui` 

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#123]
Currently cannot build due to `ui` issues, specifically `pyuic` (now) and `load_ui` (what we need)

Get the following error:
```
$ QT_API=pyqt addie
Did not convert any '.ui' files
running build
running build_py
UPDATING build/lib/addie/_version.py
set build/lib/addie/_version.py to '4.0.7+65.ge0ac1b4.dirty'
running build_scripts
copying and adjusting scripts/addie -> build/scripts-3.6
FrameworkManager-[Notice] Welcome to Mantid 3.13.20181126.1606
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Traceback (most recent call last):
  File "build/scripts-3.6/addie", line 16, in <module>
    import addie.ui_mainWindow
  File "/home/ntm/direnv/python3/addie/build/lib/addie/ui_mainWindow.py", line 1780, in <module>
    from graphicviewlib import BraggView, GofRView, SofQView
ModuleNotFoundError: No module named 'graphicviewlib'
```

**Comment by JeanBilheux** [comment]
This error has been solved by editing manually the ui file.
