### ISSUE TITLE
Right click in workspace table has some issues

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/addie#196]
It's not possible to delete a workspace for example.

**Comment by marshallmcdonnell** [comment]
Will raise the error:
```
Traceback (most recent call last):
  File "/home/ntm/direnv/python3/addie/build/lib/addie/rietveld/braggtree.py", line 256, in do_delete_gsas
    self._mainWindow.get_workflow().delete_workspace(ws_name)
  File "/home/ntm/direnv/python3/addie/build/lib/addie/addiedriver.py", line 168, in delete_workspace
    raise RuntimeError('Workspace %s does not exist.' % workspace_name)
RuntimeError: Workspace Bank 1 - 15.099999999999994 does not exist.
```

**Comment by marshallmcdonnell** [comment]
Also, when trying to "Remove from plotting" on right-click, get the following:
```
Traceback (most recent call last):
  File "/home/ntm/direnv/python3/addie/build/lib/addie/rietveld/braggtree.py", line 213, in do_remove_from_plot
    gss_bank_names)
  File "/home/ntm/direnv/python3/addie/build/lib/addie/calculate_gr/event_handler.py", line 725, in remove_gss_from_plot
    bank_id = int(gss_bank_ws.split('_bank')[-1])
ValueError: invalid literal for int() with base 10: 'Bank 1 - 15.099999999999994'
```

**Comment by marshallmcdonnell** [comment]
When we right-click to Plot the individual banks, we get:

**Comment by JeanBilheux** [comment]
When we right-click to IPython, we get the following error
![Screen Shot 2019-04-10 at 1 13 33 PM](https://user-images.githubusercontent.com/1138324/55899333-89659700-5b92-11e9-8c7a-5749eb6e67e6.png)

**Comment by Kvieta1990** [comment]
issue fixed with PR [![GitHub issue/pull request detail](https://img.shields.io/github/issues/detail/state/neutrons/addie/335)](https://github.com/neutrons/addie/issues/335)
