### ISSUE TITLE
Help buttons crash due to `MainWindow.table` attribute missing

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#282]
```python
Traceback (most recent call last):
  File "/SNS/users/ntm/direnv/python2/addie/build/lib/addie/main.py", line 644, in help_button_clicked_scans
    help_button_activator(parent=self, button_name="scans")
  File "/SNS/users/ntm/direnv/python2/addie/build/lib/addie/help_handler/help_gui.py", line 72, in help_button_activator
    o_help = HelpGui(parent=parent, button_name=button_name)
  File "/SNS/users/ntm/direnv/python2/addie/build/lib/addie/help_handler/help_gui.py", line 22, in __init__
    self.init_table()
  File "/SNS/users/ntm/direnv/python2/addie/build/lib/addie/help_handler/help_gui.py", line 26, in init_table
    self.o_table.fill()
  File "/SNS/users/ntm/direnv/python2/addie/build/lib/addie/help_handler/help_gui_table_initialization.py", line 25, in fill
    self.fill_scans()
  File "/SNS/users/ntm/direnv/python2/addie/build/lib/addie/help_handler/help_gui_table_initialization.py", line 279, in fill_scans
    if o_step2_handler.is_table_empty():
  File "/SNS/users/ntm/direnv/python2/addie/build/lib/addie/processing/idl/step2_utilities.py", line 13, in is_table_empty
    if not self.parent.ui.table.rowCount() > 0:
AttributeError: 'MainWindow' object has no attribute 'table'
```

**Comment by marshallmcdonnell** [comment]
Have another crash on clicking the "Jump There" button for NDabs:

```python
Traceback (most recent call last):
  File "/home/ntm/direnv/python3/addie/addie/help_handler/help_gui_table_initialization.py", line 175, in jump_to_step2_table
    self.parent.parent.ui.tabWidget_2.setCurrentIndex(1)
AttributeError: 'MainWindow' object has no attribute 'tabWidget_2'
```
