### ISSUE TITLE
Density == N/A crash during Launch Reduction

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#292]
The density converter is "falling over" during a `Launch Reduction` on Mantid Reduction for `addie --next` on analysis.

```python
Traceback (most recent call last):
  File "/SNS/software/addie/miniconda2/envs/addie-next/lib/python3.6/site-packages/addie/main.py", line 537, in run_mantid
    mantid_reduction_launcher.run_mantid(self)
  File "/SNS/software/addie/miniconda2/envs/addie-next/lib/python3.6/site-packages/addie/processing/mantid/launch_reduction.py", line 87, in run_mantid
    reduction_input = exporter.convert_from_row_to_reduction(json_input)
  File "/SNS/software/addie/miniconda2/envs/addie-next/lib/python3.6/site-packages/addie/processing/mantid/master_table/master_table_exporter.py", line 649, in convert_from_row_to_reduction
    element_section)
  File "/SNS/software/addie/miniconda2/envs/addie-next/lib/python3.6/site-packages/addie/processing/mantid/master_table/master_table_exporter.py", line 505, in density_selection_for_reduction
    dictionary['MassDensity'] = float(mass_density)
ValueError: could not convert string to float: 'N/A'
```

May be an issue that is already fixed, need to look at `master`

**Comment by Kvieta1990** [comment]
Issue solved with the following PR: [![GitHub issue/pull request detail](https://img.shields.io/github/issues/detail/state/neutrons/addie/346)](https://github.com/neutrons/addie/issues/346)
