### ISSUE TITLE
Calculate G(r) Tab - Save S(Q) to file

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#92]
We have the Save G(r) button to output the G(r) but lately, we have been adjust S(Q) and creating a new S(Q) workspace. We would like to shift and scale S(Q) and then be able to save it back out.

Probably near the Clear S(Q) button, can we add a Save S(Q) button?

**Comment by marshallmcdonnell** [comment]
@wdzhou has a pull request with this fix implemented. Just need to fix other issues in request and we can merge.

**Comment by marshallmcdonnell** [comment]
So, now this is not working. I get the following error:

For *.dat files:
```
Traceback (most recent call last):
  File "build/scripts-2.7/addie", line 1207, in do_save_sq
    raise RuntimeError('File type {0} cannot be recognized.'.format(file_ext))
RuntimeError: File type  cannot be recognized.
```

For *.xye files
```
Traceback (most recent call last):
  File "build/scripts-2.7/addie", line 1207, in do_save_sq
    raise RuntimeError('File type {0} cannot be recognized.'.format(file_ext))
RuntimeError: File type .xye cannot be recognized.
``

**Comment by marshallmcdonnell** [comment]
I am not sure if this is intended but the Save S(Q) button seems to be disconnected now.

**Comment by marshallmcdonnell** [comment]
`Save S(Q)` does not work and has no output.
